services:
  api:
    build: .
    deploy:
      replicas: 3
    restart: always
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: code-executor-nginx
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles

  postgres:
    image: postgres:latest
    container_name: code-executor-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent data storage

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
